
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author maaz
 */
public class PlayerGUI extends javax.swing.JFrame {

    public static Node currentTrack;
    public static Node nextTrack;
    public static Node prevTrack;
    MainClass MC = new MainClass();
    int posx = 0;
    int posy = 0;

    /**
     * Creates new form PlayerGUI
     *
     *
     */
    public PlayerGUI() {
        this.setUndecorated(true);
        this.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                posx = e.getX();
                posy = e.getY();
            }
        });

        this.addMouseMotionListener(new MouseAdapter() {
            @Override
            public void mouseDragged(MouseEvent evt) {
                //sets frame position when mouse dragged			
                setLocation(evt.getXOnScreen() - posx, evt.getYOnScreen() - posy);

            }
        });

        initComponents();

        MC.Initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        list1 = new javax.swing.JLabel();
        Display = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        list2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Next = new javax.swing.JButton();
        Previous = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Remove = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        Select = new javax.swing.JButton();
        Loop = new javax.swing.JButton();
        Stop = new javax.swing.JButton();
        Play = new javax.swing.JButton();
        Pause = new javax.swing.JButton();
        Minimize = new javax.swing.JButton();
        Close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 700));
        getContentPane().setLayout(null);

        list1.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        list1.setForeground(new java.awt.Color(246, 244, 242));
        getContentPane().add(list1);
        list1.setBounds(40, 340, 280, 40);

        Display.setFont(new java.awt.Font("Lucida Bright", 1, 15)); // NOI18N
        Display.setForeground(new java.awt.Color(246, 244, 242));
        getContentPane().add(Display);
        Display.setBounds(30, 50, 440, 30);

        jLabel3.setFont(new java.awt.Font("Suruma", 1, 24)); // NOI18N
        jLabel3.setText("Next");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 310, 110, 30);

        jLabel4.setFont(new java.awt.Font("Suruma", 1, 24)); // NOI18N
        jLabel4.setText("Previous");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 417, 90, 30);

        list2.setFont(new java.awt.Font("Lucida Bright", 0, 12)); // NOI18N
        list2.setForeground(new java.awt.Color(246, 244, 242));
        getContentPane().add(list2);
        list2.setBounds(40, 450, 270, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 735);

        Next.setText("Next");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });
        getContentPane().add(Next);
        Next.setBounds(280, 190, 80, 60);

        Previous.setText("Previous");
        Previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousActionPerformed(evt);
            }
        });
        getContentPane().add(Previous);
        Previous.setBounds(140, 190, 80, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 500, 735);

        Remove.setText("Remove");
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });
        getContentPane().add(Remove);
        Remove.setBounds(340, 360, 90, 90);

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        getContentPane().add(Add);
        Add.setBounds(329, 259, 100, 90);

        Select.setText("Select");
        Select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectActionPerformed(evt);
            }
        });
        getContentPane().add(Select);
        Select.setBounds(436, 129, 50, 50);

        Loop.setText("Loop");
        Loop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoopActionPerformed(evt);
            }
        });
        getContentPane().add(Loop);
        Loop.setBounds(20, 130, 50, 50);

        Stop.setText("Stop");
        Stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopActionPerformed(evt);
            }
        });
        getContentPane().add(Stop);
        Stop.setBounds(94, 119, 80, 80);

        Play.setText("Play");
        Play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayActionPerformed(evt);
            }
        });
        getContentPane().add(Play);
        Play.setBounds(200, 99, 110, 110);

        Pause.setText("Pause");
        Pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PauseActionPerformed(evt);
            }
        });
        getContentPane().add(Pause);
        Pause.setBounds(334, 119, 80, 80);

        Minimize.setText("-");
        Minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizeActionPerformed(evt);
            }
        });
        getContentPane().add(Minimize);
        Minimize.setBounds(430, 0, 30, 30);

        Close.setText("X");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        getContentPane().add(Close);
        Close.setBounds(470, 0, 30, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopActionPerformed
        MC.Stop();
    }//GEN-LAST:event_StopActionPerformed

    private void PauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PauseActionPerformed
        MC.Pause();
    }//GEN-LAST:event_PauseActionPerformed

    private void PlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayActionPerformed

        if (currentTrack != null && MC.playingFlag == false) {
            MC.Play(currentTrack);
        } else if (!MC.d.isEmpty() && MC.playingFlag == false) {
            MC.Play(MC.d.root);

        } else if (MC.playingFlag) {
            MC.Resume();
        }


    }//GEN-LAST:event_PlayActionPerformed

    public static void selectSong(String song) {
        
        for (int i = 0; i < MainClass.arr.length; i++) {
            if (MainClass.arr[i].getName().equals(song)) {
                
                MainClass.Stop();
                MainClass.d.clear();
                MainClass.d.insert(MainClass.arr[i]);
                MainClass.Play(MainClass.d.root);
                break;
            }

        }
    }

    public static void addSong(String name) {

        for (int i = 0; i < MainClass.arr.length; i++) {
            if (MainClass.arr[i].getName().equals(name)) {
                if (MainClass.d.isEmpty()) {
                    MainClass.d.insert(MainClass.arr[i]);
                    PlayerGUI.nextTrack = MainClass.d.root;
                    PlayerGUI.updateList();

                } else {
                    MainClass.d.insert(MainClass.arr[i]);
                    PlayerGUI.updateTracks();
                    PlayerGUI.updateList();
                    

                }
                break;
            }

        }
    }
    
    
    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed

        new DatabaseList().setVisible(true);
//        FileFilter filter = new FileNameExtensionFilter("MP3 files", "mp3", "mpeg3");
//
//        JFileChooser chooser = new JFileChooser("Tracks");
//        chooser.addChoosableFileFilter(filter);
//
//        int returnVal = chooser.showOpenDialog(null);
//
//        if (returnVal == JFileChooser.APPROVE_OPTION) {
//            //MC.Stop();
//
//            File myFile = chooser.getSelectedFile();
//            String song = myFile + "";
//
//            String name = chooser.getSelectedFile().getName();
////            list1.setText(name);
//
//            if (MC.d.isEmpty()) {
//                MC.d.insert(myFile);
//                nextTrack = MC.d.root;
//                updateList();
//                
//            } else {
//                MC.d.insert(myFile);
//                updateList();
//                updateTracks();
//            }
//        }
    }//GEN-LAST:event_AddActionPerformed

    
    
   

    public static void updateTracks() {
        if (currentTrack != null){
        nextTrack = currentTrack.next;
        prevTrack = currentTrack.prev;
        }
    }

    public static void updateList() {

        if (MainClass.d.isEmpty()) {

        } else {
            if (nextTrack == null && MainClass.loop) {
                list1.setText(MainClass.d.root.data.getName());
            } else if (nextTrack == null) {
                list1.setText("");
            } else {
                list1.setText(nextTrack.data.getName());
            }

            if (prevTrack == null && MainClass.loop) {
                list2.setText(MainClass.d.tail.data.getName());
            } else if (prevTrack == null) {
                list2.setText("");
            } else {
                list2.setText(prevTrack.data.getName());
            }
        }
    }

    private void SelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectActionPerformed

        new DatabaseList_1().setVisible(true);
//        FileFilter filter = new FileNameExtensionFilter("MP3 files", "mp3", "mpeg3", "mp4");
//
//        JFileChooser chooser = new JFileChooser("Tracks");
//        chooser.addChoosableFileFilter(filter);
//
//        int returnVal = chooser.showOpenDialog(null);
//
//        if (returnVal == JFileChooser.APPROVE_OPTION) {
//            MC.Stop();
//
//            File myFile = chooser.getSelectedFile();
//            String song = myFile + "";
//
//            String name = chooser.getSelectedFile().getName();
//            Display.setText(name);
//
//            MC.d.clear();
//            MC.d.insert(myFile);
//
//            MC.Play(MC.d.root);
//
//        }
    }//GEN-LAST:event_SelectActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CloseActionPerformed

    private void MinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizeActionPerformed
        this.setState(PlayerGUI.ICONIFIED);
    }//GEN-LAST:event_MinimizeActionPerformed

    private void LoopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoopActionPerformed
        MC.Loop();
        updateList();
    }//GEN-LAST:event_LoopActionPerformed

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
        MC.d.remove();
        updateList();
    }//GEN-LAST:event_RemoveActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        if (nextTrack != null) {
            MC.Stop();
            MC.Play(nextTrack);
        } else if (MainClass.loop) {
            MC.Stop();
            nextTrack = MainClass.d.root;
            MC.Play(nextTrack);
        }
    }//GEN-LAST:event_NextActionPerformed

    private void PreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousActionPerformed
        if (prevTrack != null) {
            MC.Stop();
            MC.Play(prevTrack);
        } else if (MainClass.loop) {
            prevTrack = MainClass.d.tail;
            MC.Stop();
            MC.Play(prevTrack);
        }
    }//GEN-LAST:event_PreviousActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PlayerGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Close;
    public static javax.swing.JLabel Display;
    private javax.swing.JButton Loop;
    private javax.swing.JButton Minimize;
    private javax.swing.JButton Next;
    private javax.swing.JButton Pause;
    private javax.swing.JButton Play;
    private javax.swing.JButton Previous;
    private javax.swing.JButton Remove;
    private javax.swing.JButton Select;
    private javax.swing.JButton Stop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel list1;
    public static javax.swing.JLabel list2;
    // End of variables declaration//GEN-END:variables
}
